# Generated by Django 6.0.2 on 2026-02-26 14:11

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='enrolled_courses',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='customuser',
            name='recommended_domain',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='question',
            name='domain',
            field=models.CharField(choices=[('Graphic Design', 'Graphic Design'), ('Content Writing', 'Content Writing'), ('Programming', 'Programming'), ('Freelancing', 'Freelancing'), ('E-Commerce', 'E-Commerce'), ('QuickBooks', 'QuickBooks'), ('AutoCAD', 'AutoCAD')], max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
