# Generated by Django 6.0.2 on 2026-04-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_enrolled_courses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='mentor_feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
