# Generated by Django 6.0.2 on 2026-04-27 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_mentor_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='latest_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
